name: challenge-one

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Print data on ubuntu
      run: echo date
  job2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print date on windows
        run: Get-Date
  job3:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Print date on macos
        run: echo date
  job4:
    needs: [job1, job2, job3]
    runs-on: ubuntu:16.04
    steps:
      - uses: actions/checkout@v2
      - name: dependence job
        run: echo date

